FROM ubuntu:14.04
MAINTAINER Raphaël Barrois <docker@r.xelmail.com>
RUN \
        echo "APT::Install-Recommends \"false\";\nAPT::Install-Suggests \"false\";\nAPT::Cache-Limit 22582912;" >> /etc/apt/apt.conf

